import Head from "next/head";
import styled from "styled-components";

import Canvas from "../components/Home/Canvas/Canvas";

const Container = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
`; 

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Dalton Perkins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas />
    </Container>
  );
}
